### PR TITLE
Fix InvalidCastException in GetAllElements method

### LINKED ISSUE #4: System.InvalidCastException: 'Unable to cast object of type 'System.Text.Json.JsonElement' to type 'System.String'.
Hey there,

I have an error with this line of code

https://github.com/PaulHatch/vault-data-protection/blob/94df233fffba283db707cd704325765813b6e9b0/src/VaultSharpDataProtection/VaultSharpXmlRepository.cs#L50

VaultSharp Version: 1.17.5.1
Microsoft.AspNetCore.DataProtection.Extensions: 8.0.11

I will make a PR to fix this issue

image

image

### PR DESCRIPTION
**Pull request by ArminShoeibi**
Fixes: https://github.com/PaulHatch/vault-data-protection/issues/4

Tests:

image

### CODE REVIEW

**Comment by ArminShoeibi** [comment]
Hi @PaulHatch ,
I hope you are doing well! Could you please review this and consider publishing a release on NuGet? Thank you in advance!

**Comment by PaulHatch** [comment]
Hey @ArminShoeibi ,
Thanks for the contribution. It's been some time since I looked at this since we moved away from using Vault, but I guess the underlying API is now returning a `JsonElement` rather than something cast-able to `string`?

There's an opportunity for a bit more pattern matching here:

```sharp
public IReadOnlyCollection<XElement> GetAllElements()
    {
        try
        {
            var response = RunSync(() => _vault.V1.Secrets.KeyValue.V2.ReadSecretAsync(_path, null, _mountPoint));
            return response.Data.Data.Values.Select(e => e switch
                {
                    string v => XElement.Parse(v), // this line might not be necessary is string is never returned now
                    JsonElement {ValueKind: JsonValueKind.String} j when j.GetString() is var s => XElement.Parse(s),
                    _ => throw new InvalidCastException($"Expected JSON string, but got {e.GetType()}.")
                }).ToList()
                .AsReadOnly();
        }
        catch (VaultApiException e) when (e.StatusCode == 404)
        {
            return Array.Empty<XElement>();
        }
    }
```


The test here is requiring a running Vault server on localhost, which isn't something (easily) available to the CI service. The test runs as part of the build script, so this will fail and can't be published as is even if merged. A mock could be used instead.

**Comment by ArminShoeibi** [comment]
> Hey @ArminShoeibi , Thanks for the contribution. It's been some time since I looked at this since we moved away from using Vault, but I guess the underlying API is now returning a `JsonElement` rather than something cast-able to `string`?
> 
> There's an opportunity for a bit more pattern matching here:
> 
> ```
> public IReadOnlyCollection<XElement> GetAllElements()
>     {
>         try
>         {
>             var response = RunSync(() => _vault.V1.Secrets.KeyValue.V2.ReadSecretAsync(_path, null, _mountPoint));
>             return response.Data.Data.Values.Select(e => e switch
>                 {
>                     string v => XElement.Parse(v), // this line might not be necessary is string is never returned now
>                     JsonElement {ValueKind: JsonValueKind.String} j when j.GetString() is var s => XElement.Parse(s),
>                     _ => throw new InvalidCastException($"Expected JSON string, but got {e.GetType()}.")
>                 }).ToList()
>                 .AsReadOnly();
>         }
>         catch (VaultApiException e) when (e.StatusCode == 404)
>         {
>             return Array.Empty<XElement>();
>         }
>     }
> ```
> 
> The test here is requiring a running Vault server on localhost, which isn't something (easily) available to the CI service. The test runs as part of the build script, so this will fail and can't be published as is even if merged. A mock could be used instead.

You’re right @PaulHatch, the API now returns a JsonElement instead of a string.

I appreciate the pattern-matching suggestion I have committed to that change..

Regarding the test, you’re correct that it currently depends on a running Vault server locally, which isn't ideal for CI. Would it be possible to disable this specific test in the CI pipeline? Alternatively, we could explore using TestContainers to mock the Vault server, allowing the test to run without requiring a live instance.

**Comment by PaulHatch** [comment]
OK, so let's add something like `[Fact(Skip = "Requires a running Vault server")]` to the test, then it can be released.

**Comment by ArminShoeibi** [comment]
> OK, so let's add something like `[Fact(Skip = "Requires a running Vault server")]` to the test, then it can be released.

Thanks @PaulHatch , It's done.

**Pull request merged**
